const env = {};
for (const key of [
  'CANARY',
  'DEPLOY_BRANCH',
  'DRY_RUN',
  'GITHUB_REPOSITORY',
  'GITHUB_REPOSITORY_OWNER',
  'GITHUB_REPOSITORY_NAME',
  'DEPENDENCY_ROLLINGVERSIONS_TEST_CUSTOM_SCRIPTS_NPM_GITHUB_ACTIONS_A',
  'DEPENDENCY_ROLLINGVERSIONS_TEST_CUSTOM_SCRIPTS_NPM_GITHUB_ACTIONS_B',
  'NEW_VERSION',
]) {
  env[key] = process.env[key];
}
console.log('DEPLOYING API', env);
